Iter20
lammer90/shortener pull request #26
Opened 2024-03-14 10:15 UTC by lammer90

Iter20

2024-03-18 16:33 UTC, s-shpak requested changes

2024-03-18 16:33 UTC, s-shpak commented on cmd/shortener/main.go
> +	fmt.Printf("version=%s, time=%s, commit=%s\n", buildVersion, buildDate, buildCommit)
Используй здесь логгер, а не пакет `fmt`

2024-03-18 16:33 UTC, s-shpak commented on cmd/staticlint/main.go
> +		if fn.Pkg.Pkg.Name() == "main" && fn.Name() == "main" {
Попробуй уменьшить вложенность этой функции - выходи раньше, если проверка не проходит

2024-03-18 16:33 UTC, s-shpak commented on cmd/staticlint/mycheck
Это не должно попадать в репозиторий

2024-03-18 16:33 UTC, s-shpak commented on cmd/shortener/main.go
> +	buildVersion = "N/A"
Добавь инструкции в README.md о том, как определять эти переменные

2024-03-20 05:28 UTC, lammer90 commented on cmd/shortener/main.go
> +	fmt.Printf("version=%s, time=%s, commit=%s\n", buildVersion, buildDate, buildCommit)
поправил

2024-03-20 05:28 UTC, lammer90 commented on cmd/staticlint/main.go
> +		if fn.Pkg.Pkg.Name() == "main" && fn.Name() == "main" {
поправил

2024-03-20 05:28 UTC, lammer90 commented on cmd/staticlint/mycheck
убрал

2024-03-20 05:28 UTC, lammer90 commented on cmd/shortener/main.go
> +	buildVersion = "N/A"
добавил

2024-03-22 14:53 UTC, s-shpak approved these changes

2024-03-30 11:31 UTC, merged